"""Phase 3b: evaluate the registered cohort criteria on the DRAWN cohort.

Every criterion is recomputed from cohort/cohort_cells.csv and reported as the
computed value next to its threshold. A3 and A4 were kept as backstops that
hold by construction; here they are executed, so a broken draw fails loudly
instead of passing silently. Exit status is non-zero if any check fails.
"""
import argparse
import sys
from fractions import Fraction

import pandas as pd

ORIGINS = ("tumor_primary", "normal_adjacent")
C_MIN = 100
C_TRAIN = 300
A1_MIN_DONORS = 12
A3_MAX_SHARE = Fraction(1, 4)
A4_TRAIN_MAX_RATIO = Fraction(3)


def checks(c):
    """Return a list of (criterion, computed value, threshold, passed)."""
    out = []
    a = c[c.in_analysis100]
    pool = c[c.in_pool300]

    out.append(("no duplicate cell_id", int(c.cell_id.duplicated().sum()), "0",
                not c.cell_id.duplicated().any()))
    nested = bool((~c.in_pool300 & c.in_analysis100).sum() == 0)
    out.append(("analysis cohort nested in training pool", nested, "True", nested))
    origins = sorted(c.origin.unique())
    out.append(("F2 origins are exactly the two registered sites", origins,
                sorted(ORIGINS), origins == sorted(ORIGINS)))

    donors_by_origin = {o: set(a[a.origin == o].donor_id) for o in ORIGINS}
    paired = donors_by_origin[ORIGINS[0]] == donors_by_origin[ORIGINS[1]]
    out.append(("F3 every analysis donor present on both sides (paired)", paired, "True", paired))

    assays = c.groupby(["donor_id", "origin"]).assay.apply(lambda s: tuple(sorted(set(s))))
    per_donor = assays.unstack()
    same_assay = bool((per_donor[ORIGINS[0]] == per_donor[ORIGINS[1]]).all())
    all_10x = bool(c.assay.str.startswith("10x").all())
    out.append(("F4 all cells 10x", all_10x, "True", all_10x))
    out.append(("F4 assay set identical on both sides per donor", same_assay, "True", same_assay))

    for o in ORIGINS:
        ao = a[a.origin == o]
        n = ao.groupby("donor_id").size()
        n_g = len(n)
        out.append((f"A1 [{o}] qualifying donors", n_g, f">= {A1_MIN_DONORS}", n_g >= A1_MIN_DONORS))
        out.append((f"A2 [{o}] analysis cells per donor (min, max)", (int(n.min()), int(n.max())),
                    f"== {C_MIN} each", bool((n == C_MIN).all())))
        ratio = Fraction(int(n.max()), int(n.min()))
        out.append((f"A4 [{o}] analysis max/min donor cells", str(ratio), "== 1 exactly", ratio == 1))
        share = Fraction(int(n.max()), int(n.sum()))
        out.append((f"A3 [{o}] largest donor share of analysis cells", f"{share} = {float(share):.4f}",
                    f"<= 1/4 and == 1/n_g = 1/{n_g}",
                    share <= A3_MAX_SHARE and share == Fraction(1, n_g)))
        pn = pool[pool.origin == o].groupby("donor_id").size()
        pratio = Fraction(int(pn.max()), int(pn.min()))
        out.append((f"A4 [{o}] training-pool max/min donor cells", f"{pratio} = {float(pratio):.3f}",
                    f"<= {A4_TRAIN_MAX_RATIO}", pratio <= A4_TRAIN_MAX_RATIO))
        out.append((f"A4 [{o}] training-pool cells per donor capped", int(pn.max()), f"<= {C_TRAIN}",
                    int(pn.max()) <= C_TRAIN))
    return out


def report(results, title="Cohort QC"):
    lines = [f"# {title}", "",
             "Computed values, not expected ones. Generated by `scripts/qc_cohort.py`.", "",
             "| Criterion | Computed | Threshold | Pass |", "|---|---|---|---|"]
    for name, value, thr, ok in results:
        lines.append(f"| {name} | {value} | {thr} | {'PASS' if ok else '**FAIL**'} |")
    lines += ["", f"All passed: **{all(r[3] for r in results)}**", ""]
    return "\n".join(lines)


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--cohort", required=True)
    p.add_argument("--out", required=True)
    a = p.parse_args()
    c = pd.read_csv(a.cohort)
    results = checks(c)
    text = report(results)
    open(a.out, "w").write(text)
    print(text)
    return 0 if all(r[3] for r in results) else 1


if __name__ == "__main__":
    sys.exit(main())
